sudo: true
language: perl
os:
  - linux
perl:
   - 'blead'
   - '5.24'
   - '5.22'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
   - '5.8'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
   include:
      - perl: '5.24'
        env: COVERAGE=1
addons:
   apt:
      packages:
      - libsnmp-dev
# Dist::Zilla would make this easier
before_install:
# for some reason, travis-perl doesnt work out that it needs to install:
  - cpanm --quiet --notest Net::SNMP
  - perl Makefile.PL; make listalldeps | cpanm --quiet --notest
  - eval $(curl https://travis-perl.github.io/init) --auto
