sudo: true
language: perl
os:
  - linux
perl:
   - 'blead'
   - '5.22-shrplib'
#   - '5.22'
#   - '5.20'
#   - '5.18'
#   - '5.16'
#   - '5.14'
#   - '5.12'
#   - '5.10'
#   - '5.8'
matrix:
   allow_failures:
      - perl: 'blead'
#      - perl: '5.8'
   fast_finish: true
#   include:
#      - perl: '5.20'
#        env: COVERAGE=1
before_install:
  - wget https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz
  - tar zxvf net-snmp-5.7.3.tar.gz
  - cd net-snmp-5.7.3
  - ./configure --with-default-snmp-version="3" --with-sys-contact="@@no.where" --with-sys-location="Unknown" --with-logfile="/var/log/snmpd.log" --with-persistent-directory="/var/net-snmp"
  - make
  - sudo make install
  - chown -R travis:travis .
  - cd perl
  - cpanm --verbose .
  - cpanm --notest --verbose Crypt::DES   Crypt::Rijndael  Digest::HMAC  Digest::SHA1  Socket6
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - cd ..
  - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
  - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
  - dzil smoke --release --author

